name: Terraform Destroy 

on:
  workflow_dispatch:
    inputs:
      env:
        description: 'Environment to destroy to'
        required: true
        default: 'dev'
        type: choice
        options:
          - dev
          - prod

permissions:
  id-token: write
  contents: read


jobs: 
  destroy: 
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: app.tf #set the working directory for the terraform

    environment: ${{ github.ref_name }} #get correct the environment <dev or main >
    
    steps:
      - name: Checkout 
        uses: actions/checkout@v4
      
      - name: Configuration the AWS Credential 
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: ${{ secrets.aws_rta }}
          aws-region: ${{ secrets.AWS_REGION }}
          role-session-name: cuongnvecl-github-svc-tf-destroy-infra

      - name: Setup terraform
        uses: hashicorp/setup-terraform@v3
        with:
          cli_version: v1.11.3 #verify with your end terraform version

      - name: Terraform init
        run: terraform init -backend-config="key=github_ci/infra/${{ github.ref_name }}-provisionecl1.tfstate -reconfigure"

      - name: Terraform Plan destroy depends on env and confirmation
        if: github.event.inputs.confirmation == 'Confirm' && github.event.inputs.env == 'dev'
        run: |
          terraform workspace select ${{ github.event.inputs.env }} 
          terraform plan -destroy --var-file=envs/${{ github.event.inputs.env }}.tfvars
       
      # - name: Terraform destroy depends on env and confirmation
      #   if: github.event.inputs.confirmation == 'Confirm' && github.event.inputs.env == 'dev'
      #   run: |
      #     terraform workspace select ${{ github.event.inputs.env }} 
      #     terraform destroy -auto-approve --var-file=envs/${{ github.event.inputs.env }}.tfvars

      - name: Check Confirmation 
        if: github.event.inputs.confirmation != 'Confirm'
        run: | 
          echo "Confirmation not provided. Skipping terraform destroy."  
          exit 1