name: Reports

on:
  workflow_dispatch:
    inputs:
      env:
        description: 'Run to export the reports'
        required: true
        default: 'reports'
        type: choice
        options:
          - reports

env:
  ENV: ${{ github.event.inputs.env }}

permissions:
  contents: read
  id-token: write


jobs:
  verify:
    name: Verify Environment
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: ${{ secrets.aws_rta }}
          aws-region: ${{ secrets.AWS_REGION }}
          role-session-name: cuongnvecl-github-svc-tf-provision-infra  

      - name: Update kube config
        run: aws eks update-kubeconfig --name ${{ secrets.EKS_CLUSTER_NAME }} --region ${{ secrets.AWS_REGION }}

      - name: Showing the results
        run: |
          echo "kubectl get pods -A -o wide"
          kubectl get pods -A -o wide
          echo " "
          echo "kubectl get pods -n max-weather-dev"
          kubectl get pods -n max-weather-dev
          echo " "
          echo "kubectl get pods -n max-weather-staging"
          kubectl get pods -n max-weather-staging
                    echo " "
          echo "kubectl get pods -n max-weather-prod"
          kubectl get pods -n max-weather-prod
          echo " "
          echo "kubectl get namespace "
          kubectl get namespace 

          



