name: Results

on:
  workflow_dispatch:
    inputs:
      env:
        description: 'Run to show the results'
        required: true
        default: 'dev'
        type: choice
        options:
          - dev
          - prod

env:
  ENV: ${{ github.event.inputs.env }}

permissions:
  contents: read
  id-token: write


jobs:
  verify:
    name: Verify Environment
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: ${{ secrets.aws_rta }}
          aws-region: ${{ secrets.AWS_REGION }}
          role-session-name: cuongnvecl-github-svc-tf-provision-infra  

      - name: Verify alp on AWS
        run: |
          kubectl get pods -A
          kubectl get pods -n max-weather-${{ github.event.inputs.env }}
          

      # - name: Verify Pod Status
      #   run: |
      #     echo "Verify Pod Status"
      #     echo "kubectl get pods -n max-weather-${{ github.event.inputs.env }}"
      #     kubectl get pods -n max-weather-${{ github.event.inputs.env }} 

      #     echo "kubectl logs -n max-weather-${{ github.event.inputs.env }} <pod-name>"

      #     echo "kubectl get endpoints -n max-weather-${{ github.event.inputs.env }} svc-backend-api"
      #     kubectl get endpoints -n max-weather-${{ github.event.inputs.env }} svc-backend-api 


